name: '1.1.0.$(rev:r)'

trigger:
  - master

stages:
- stage: 'build'
  jobs:
  - job: 'build_job'
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
    - checkout: self
      clean: true
      
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install --only=dev
        npm install
        npm run build-all
      displayName: 'npm install and run all build scripts'